name: Deploy React App to AWS EC2 and run Docker container

on:
  push:
    branches:
      - develop
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: fambudget/fambudget_react_front:latest

  Deploy:
    needs: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
            DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USER }}
            DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            PRIVATE_KEY: ${{ secrets.SSH_AWS_FAMBUDGET  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}

        run: |
           echo "$PRIVATE_KEY" > fambudget.pem && chmod 600 fambudget.pem
           ssh -o StrictHostKeyChecking=no -i fambudget.pem ${USER_NAME}@${HOSTNAME}    ' 
             docker login --username=${DOCKER_HUB_USERNAME} --password=${DOCKER_HUB_PASSWORD}
             sudo docker stop fambudget_react_front
             sudo docker rm fambudget_react_front
             sudo docker rmi fambudget/fambudget_react_front
             sudo docker run -d --name 'fambudget_react_front' -p 3000:3000 fambudget/fambudget_tract_front:latest
            '
